### ISSUE TITLE
Automating the Importation of Products

### ISSUE THREAD

**Issue by mwpowellhtx** [OrchardCMS/OrchardCore.Commerce#102]
Question concerning support for _importation_ of `Product`. I am assuming this may be able to happen at a time of site publication using one of the appropriate _Content Part_ handler phase lines? That is one potential scenario.

Better would be the possibility for _importing dynamically_ at _site runtime_, i.e. post-publication, i.e. from a _spreadsheet asset_, or _database_, etc. But I'm not sure this is the way _OC_ or _Commerce_ function.

Or for that matter, if there is actually an _OC Workflow_ around that moment.

Open to 💡 ideas, 🍺 suggestions, 🧠 thoughts?

Thanks...

**Comment by bleroy** [comment]
Those are really Orchard Core questions, not Commerce-specific.

Orchard Core Workflows documentation: https://docs.orchardcore.net/en/latest/docs/reference/modules/Workflows/

To import data, see https://docs.orchardcore.net/en/latest/docs/reference/modules/Recipes/ and https://docs.orchardcore.net/en/latest/docs/reference/modules/Deployment/
