### ISSUE TITLE
Inconsistent currency configuration after setup (OCC-17)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#105]
While trying out the module I was surprised to see it says "Can't add product sample because it doesn't have a price." when trying to add it to the cart, even though I have correctly set up a USD price:
![image](https://user-images.githubusercontent.com/4007293/162627623-f8b295e6-deed-4c14-9078-a21c1d6e3824.png)

When I go to /Admin/Settings/commerce both currency options are shown to be "USD", but when I place a breakpoint in `MoneyService.CurrentDisplayCurrency` it actually says the value is `---`:
![image](https://user-images.githubusercontent.com/4007293/162627726-1680e7bc-05fc-4a65-9949-0e226b32465b.png)
(By the way, since `_currencySelector.CurrentDisplayCurrency` is not `null` by default I don't think the `?? DefaultCurrency` is ever used.)

Looks like the frontend works correctly but the admin config gets the wrong default. If I click the Save button in the Commerce settings without touching anything it gets updated to USD and starts to behave as expected.

**Comment by DemeSzabolcs** [comment]
This problem is only present when the `Orchard Core Commerce Settings Currency Selector` feature is enabled. `_currencySelector.CurrentDisplayCurrency` 's value is `null` by default, but when that feature is enabled, it gets converted:

```
public class CommerceSettingsCurrencySelector : ICurrencySelector
{
    private readonly CommerceSettings _options;

    public ICurrency CurrentDisplayCurrency => Currency.FromIsoCode(_options.CurrentDisplayCurrency);

    public CommerceSettingsCurrencySelector(IOptions<CommerceSettings> options) => _options = options.Value;
}
```

`Currency.FromIsoCode()` converts it to `Unspecified` currency which is not `null`, therefore `DefaultCurrency` cannot take over.
