### ISSUE TITLE
Allow Admin Orders (OCC-54)

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore.Commerce#11]
The admin interface should allow for order creation, it doesn't need to take payments, but is nice to have available for posting orders which come in through offline sales. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-54)

**Comment by DAud-IcI** [comment]
Currently you can add order content items, but the line item list is not editable. (The payment info isn't editable either, but I think that should remain read-only.) There is a more specific issue just about editing the line items (#117) that we plan to address in the near future, so I'm closing this. Feel free to follow the linked issue if you are still interested.
