### ISSUE TITLE
Add OrderPart permissions (OCC-67)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#115]
https://github.com/OrchardCMS/OrchardCore.Commerce/blob/e9dba990fbf2359dffa5af31126a800e59ad4118/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs#L28-L32
(This issue was created as part of the effort to externalize TODOs from the code base.)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-67)

**Comment by porgabi** [comment]
What permissions are needed here?

**Comment by DAud-IcI** [comment]
tbh I'm not sure, because ManageOrders would be for editing, not display.

@bleroy I see it's [by you](https://github.com/OrchardCMS/OrchardCore.Commerce/commit/a9754851739308fa5f737bbbd70c284ccf4e6e1c), although from 3 years ago. Do you happen to remember what this comment was about?

**Comment by bleroy** [comment]
Only the specific customer and order managers should have access to an order. Not sure where the best place to enforce that is.

**Comment by DAud-IcI** [comment]
Thanks, Bertrand! I agree, non-manager users shouldn't have access to each others' orders for the sake of confidentiality.
