### ISSUE TITLE
Orchard Core Commerce MVP planning and survey

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore.Commerce#123]
Hi everyone, we are almost ready to kick off the Orchard Core Commerce MVP development here at Lombiq (see the announcement about the stewardship [here](https://github.com/OrchardCMS/OrchardCore.Commerce/discussions/120)). I'd like to ask everyone who's planning to build an e-commerce website using the Orchard Core Commerce module to take this short survey and let us know what features you'd need the most so that we can focus on the important things first.

Survey: https://forms.office.com/r/TrE86CMbz2

**Comment by haohello** [comment]
Can you release before 2025?

**Comment by barthamark** [comment]
Yes, we can release it before 2025. :)

**Comment by DAud-IcI** [comment]
Check out [this discussion](https://github.com/OrchardCMS/OrchardCore.Commerce/discussions/142) for the results and followup.
Note that the MVP is for short term goals (e.g. within the year). Plenty more can still happen until 2025.
