### ISSUE TITLE
Use existing CI workflows from Lombiq/GitHub-Actions instead of custom one (OCC-19)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#128]
Instead of custom steps in [pr_ci.yml](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/.github/workflows/pr_ci.yml), we can just use [build-and-test-orchard-core.yml](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/build-and-test-orchard-core.yml). See [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/build-and-test.yml#L11-L16), for an example.

**Comment by Skrypt** [comment]
It adds a dependency on the Lombiq repository which I'm not sure about.

**Comment by DAud-IcI** [comment]
It's normal to use external dependencies for composing GHA workflows. `Lombiq/GitHub-Actions` is actively developed, specifically for OC CI tasks so it has better feature set compared to a custom workflow. If you are uncomfortable with using external workflows, I think it would be preferable for `OrchardCMS` to fork it (and ofc periodically update it from upstream) rather than to reinvent the wheel.

**Comment by Skrypt** [comment]
Yes, but since Lombiq is a company and that Orchard Core is an open source project I think we need to draw a line between both.
See here the Licence : https://github.com/Lombiq/GitHub-Actions/blob/dev/Licence.md

**Comment by Piedone** [comment]
The license is BSD 3-clause, an OSS license. What issue do you see OCC using an OSS project of Lombiq, in contrast to any other OSS dependency?

**Comment by Skrypt** [comment]
Thanks for comfirming @Piedone 
I did not read all the details, I just saw Lombiq and looked liked a custom licence since Github did not find the matching.
