### ISSUE TITLE
Settings and editor crash when Localization feature is enabled.

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#129]
Steps:
- Set up the site with the _OrchardCore Commerce - Development_ recipe.
- Go to Admin > Configuration > Features.
- Enable _Orchard Core Commerce_ and _Localization_ features. It doesn't seem to matter if the other Commerce features are enabled.
- Go to Admin > Configuration > Settings > Commerce
- Error page is shown.
  ![image](https://user-images.githubusercontent.com/4007293/181908338-183b0575-4145-4810-9252-59cc29f6db64.png)
- Go to Admin > Content > Content Items and click New > Order.
- Error page is shown.
  ![image](https://user-images.githubusercontent.com/4007293/181908541-89fa91c9-3612-4019-8435-3aee2944af71.png)

The problem is likely with this `¤¤` currency, because it's `EnglishName` is an empty string:

![image](https://user-images.githubusercontent.com/4007293/181908735-7cae3549-48ae-47eb-885c-eb0f3ba492f0.png)

**Comment by agriffard** [comment]
We should reference it as an issue in the main repo.

**Comment by DAud-IcI** [comment]
Do you mean that `IStringLocalizer<PricePartSettingsDisplayDriver>[""]` throwing an exception is a bug too?
