### ISSUE TITLE
Add UI tests for checkout and payment (OCC-21)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore.Commerce#130]
Followup to #127 (technical debt). Tasks:
- mock the Stripe services like `PaymentIntentService`
- include Stripe.js via NPM module instead of direct loading from their site ([see](https://github.com/stripe/stripe-js))
- add UI tests for the checkout
- add a samples recipe that contains some products and pre-existing offers to help with future UI tests

**Comment by Piedone** [comment]
Doesn't https://github.com/OrchardCMS/OrchardCore.Commerce/issues/149 cover this?

**Comment by sarahelsaig** [comment]
Yeah, everything listed in the description is covered. by that issue.
