### ISSUE TITLE
Separate Stripe payment into a feature so it can be disabled if other payment provider is desired. (OCC-63)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore.Commerce#149]
This won't be urgent until we have other payment providers. If someone needs it soon because you already have your own payment implementation, please comment on this issue.

- Refactor the Stripe payment processor logic into a separate project, e.g. OrchardCore.Commerce.PaymentProcessors.Stripe.
- Create the necessary abstraction to make it provider-based with Stripe being just one provider.
  - Replace the `~/cart`'s <kbd>Checkout</kbd> button with a <kbd>Checkout with {providerName}</kbd> button so it's locked down in the order form. Then only display the correct form for that processor.
  - Use the `IPaymentProvider` and `IPayment` interfaces.
- Add a dummy payment processor provider.
  - This should be a separate feature.
  - It should be enabled in the recipe but (if possible) force-disabled in production.
  - Add a sample `Order` content item to the recipe, whose payment info references this provider.
- Include which payment provider was used in the `OrderPart`.
  - Make it read-only if the Order is already created and this has been set.

Also create a unit test of the basic purchase flow using the dummy payment processor. 
- Buy different amounts of the two sample products.
- Change the amount of one in the cart.
- Fill the checkout form.
- Go to the newly created Order item.
- Verify that the order has the correct products an amounts, and that the correct payment provider name is displayed.

If #155 is resolved, then also set the addresses, and verify that they are valid as well. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-63)

**Comment by hishamco** [comment]
I'm working on a project that uses a sort of eCommerce, I agree to separate Stripe payment but not as a feature. It could be as the following:

- OCC.Payment.Abstractions
- OCC.Payment.Core (Stripe Payment Implementation)
- OCC.Payment (Module)

This way it will be much flexible and extensible

**Comment by DAud-IcI** [comment]
It would be important to be able to disable unused payment implementations. For example if we have Stripe for production and a dummy payment processor for UI testing. I suggested using features because that seems like a natural fit for this purpose in OC. Do you have something else in mind?

**Comment by hishamco** [comment]
`OCC.Payment` module will have the default implementation, so it could be enabled and disabled. As a user, I can create `OCC.Payments.PayPal` enable it and disable the other provider

In another scenario, some websites might support multiple gateway providers

**Comment by hishamco** [comment]
`OCC.Payment` module will have the default implementation, so it could be enabled and disabled. As a user, I can create `OCC.Payments.PayPal` enable it and disable the other provider

In another scenario, some websites might support multiple gateway providers

**Comment by hishamco** [comment]
At the end each module has a default feature which you can enable or disable, but I'd prefer creating modules instead of adding the payment providers into a single one
