### ISSUE TITLE
Shopping cart widget (OCC-38)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#160]
Create a widget that indicates the count of your shopping cart and clicking on it sends you to the cart.
No need for a dropdown preview, keep it simple.

The cart icon could be [`cart-shopping` from Font-Awesome](https://fontawesome.com/v6/icons/cart-shopping?s=solid) with a number next to it, so there is no need for custom graphics either.

Add it to the setup recipe and verify that it works in a UI test. If possible, extend an existing UI test rather than creating a new one.

**Comment by DemeSzabolcs** [comment]
Do we need the total too or just the count of the items?

**Comment by DAud-IcI** [comment]
Just the count.
