### ISSUE TITLE
Payment infrastructure (OCC-49)

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/OrchardCore.Commerce#17]
Payment services provide a method to charge the customer, and a flag to switch to simulation mode. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-49)

**Comment by MatteoPiovanelli-Laser** [comment]
Dropping here the link to the PaymentGateway module we made for good old Orchard:
https://github.com/LaserSrl/Laser.Orchard.Platform/tree/master/src/Modules/Laser.Orchard.PaymentGateway

In the same repo there are a few implementations. THe one that's more relevant here is probably Braintree. There are others for a couple services specific to Italian banks.

In the NwazetIntegration module there there should be stuff that allows implementations of the PaymentGateways to work with Nwazet. This was a thing we did to avoid rewrites in Nwazet that would make it dependent on our modules.

**Comment by bleroy** [comment]
This is of interest both as an upcoming W3C standard to be aware of, but also as a design blueprint.

https://www.w3.org/TR/payment-request/

**Comment by Piedone** [comment]
Isn't this done, @sarahelsaig?

**Comment by sarahelsaig** [comment]
Yeah. We have the dummy provider instead of the simulation mode, but it's close enough.
