### ISSUE TITLE
UI tests don't use fixed culture (OCC-80)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#177]
### Describe the bug

You get problems, like the decimal point, see below. 

### To Reproduce

1. Create a UI test that edits a product, sets the price to "1.5" for example and then publishes.
2. Switch your computer's locale to en-US and run it.
3. Switch your computer's locale to hu-HU and run it,

Step 3 will fail because Hungarian locale uses comma as decimal separator instead of period.

### Expected behavior

Tests should be set up with a fixed culture for portability, even when the Localization feature is disabled. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-80)

**Comment by Piedone** [comment]
Do this: https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/TestableOrchardCoreApps.md#:~:text=By%20default%2C%20the%20culture%20settings%20used%20when%20setting%20up%20an%20Orchard%20site%20depend%20on%20the%20host%20machine%27s%20culture.
