### ISSUE TITLE
Feature properties are inconsistent (OCC-91)

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore.Commerce#196]
### Describe the bug

The features "Orchard Core Commerce", "Orchard Core Commerce Session Cart Storage", "Orchard Core Commerce Settings Currency Selector" are all under the Commerce category and use the same name pattern. The features "Orchard Core Commerce - Tax" and "OrchardCore.Commerce.ContentFields" both use different naming patterns, and are under the Content Management feature.

### To Reproduce

Search for "commerce" under the Features admin page.

### Expected behavior

- All OCC features under the Commerce category.
- Consistent naming pattern. I recommend "Orchard Core Commerce - <feature name>".

### Screenshots

![image](https://user-images.githubusercontent.com/1976647/193419494-39163348-55bd-47fc-a333-5439eb6defd6.png)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-91)

**Comment by DAud-IcI** [comment]
Good point, Same for the recipes too.
