### ISSUE TITLE
Orchard Core features

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#20]
Do you have any ideas about how you will use the features provided by Orchard Core?
Some of them are new compared to Orchard 1.x.

Here is a list of some available features:

Recipes, Deployment steps, Import/Export
	
Global and custom Settings

Security:	
- Authentication
- 	Profile: User properties
- 	Roles, Permissions
- 	Open Id, Social logins

Content parts and fields:
- 	Display and edit modes
- 	MediaField
- 	ContentPicker
- 	PredefinedList

Media, Assets
	
GraphQL, JsonAPI

Navigation:

- 	Autoroute
- 	Menu
- 	Taxonomies

Theming:

- 	Alternates
- 	Placement
- 	Shapes

Liquid:

- 	Filters
- 	Templates

Indexing, Search:

- 	Lucene
- 	Queries

Layers, Widgets

- 	Recommended articles
- 	Search filters

Workflows

- 	Activities
- 	Events
- 	Tasks

**Comment by bleroy** [comment]
Yes. That's also how Nwazet was built: leverage Orchard features whenever possible. Our plan is to use workflows a lot more, in particular.

Reversely, if we need a feature that is not commerce-specific, we'll contribute it to Orchard Core instead. An example was the reporting in Nwazet.
