### ISSUE TITLE
Currency sign is not displayed correctly because culture is not correct (OCC-98)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#205]
### Describe the bug

While most countries write e.g. the € sign before the value it is displayed after the value currently.

### To Reproduce

1. Go to any page where the value of a product is displayed.
2. The value and sign is displayed in the wrong order.
3. Debug `Currency.ToString()`  You can see `ast-ES` culture for € for some reason.

### Expected behavior

Correct order for currency signs and values.

### Screenshots

![image](https://user-images.githubusercontent.com/19938236/196042429-c9b7f7df-983c-4a26-b01a-9d3ee798a5e8.png)
![image](https://user-images.githubusercontent.com/19938236/196042432-8fe9b3b8-bb47-46b5-98dd-292aabee7f9c.png)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-98)

**Comment by DAud-IcI** [comment]
For me the `Culture` is Cherokee American. How weird...
![image](https://user-images.githubusercontent.com/4007293/196065603-4978fc92-98cb-4521-a7be-6ade5203e39e.png)

**Comment by wAsnk** [comment]
Isn't this filtering out everything except the first culture that has the currency? This comparer is used on line 40th in `KnownCurrencyTable` where the cultures are also collected.

```csharp
private sealed class CurrencyEqualityComparer : IEqualityComparer<ICurrency>
    {
        public bool Equals(ICurrency left, ICurrency right) =>
            (left is null && right is null) ||
            StringComparer.OrdinalIgnoreCase.Equals(left?.CurrencyIsoCode, right?.CurrencyIsoCode);

        public int GetHashCode(ICurrency obj) => StringComparer.OrdinalIgnoreCase.GetHashCode(obj.CurrencyIsoCode);
    }
```

**Comment by DAud-IcI** [comment]
It definitely looks like using the currency's `CultureInfo` is not appropriate here. The number should be formatted according to the viewer's culture not one random culture that uses that currency. This is especially problematic for Euro, where some cultures use period while others use comma for the decimal separator.
