### ISSUE TITLE
New user can't access checkout page (OCC-99)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#206]
### Describe the bug

Authenticated role should have Checkout by default. Currently, a new user after successful registration will land on a no access page.

### To Reproduce

1. Be signed out.
2. Add items to the cart.
3. Checkout
4. Register new user
5. Return URL redirects to checkout page
6. Gets no access page.

### Expected behavior

After a successful registration during checkout, the user (Authenticated role) should get Checkout permission.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-99)

**Comment by DAud-IcI** [comment]
I don't think this is a bug. OCC is more of a toolkit than a turnkey webshop, so you are expected to make up your mind about your security and business process, and tweak your setup recipe accordingly. Some consumers might not want to grant the permission to Authenticated but give it to a more restricted role that's manually applied (e.g. wholesalers or sellers of controlled products).
