### ISSUE TITLE
New fields of OrderPart are not shown (OCC-101)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#211]
### Describe the bug

There was a change on how OCC shows the checkout page and that caused a bug that prevents showing new fields on the checkout page. Currently if you add a new field to the OrderPart it is not shown.

### To Reproduce

1. Add a new field to OrderPart through the UI
2. Add a product to cart then checkout
3. Newly added field is missing, due to the custom shape.

### Expected behavior

When you add a new field to the OrderPart it should show up on the checkout page, on the successful payment page, on the order content item editor and view. So basically where the OrderPart is used.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-101)

**Comment by DemeSzabolcs** [comment]
I think this is not a bug in the sense, that I think the checkout page can't really be dynamic. It was because it used the admin editor, but that wasn't working out really well, so we can't do that. I think the current checkout page is overridable though.

**Comment by wAsnk** [comment]
Could you check this please? @DAud-IcI

**Comment by DAud-IcI** [comment]
Maybe the fields should be rendered using a custom DisplayType, e.g. `await _contentItemDisplayManager.BuildDisplayAsync(order, _updateModelAccessor.ModelUpdater, "Checkout");`

**Comment by wAsnk** [comment]
Consider validation problems as well when fixing this.
https://github.com/OrchardCMS/OrchardCore.Commerce/issues/218

**Comment by DAud-IcI** [comment]
> Consider validation problems as well when fixing this.

Luckily the two are non-overlapping.
