### ISSUE TITLE
Upgrade to the latest version of Lombiq.Tests.UI (OCC-102)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#212]
### Is your feature request related to a problem? Please describe

The version currently used runs the tested webapp as a separate process (harder to debug) whereas version [4.0.1](https://www.nuget.org/packages/Lombiq.Tests.UI/4.0.1) uses `WebApplicationFactory` to instantiate the webapp in the same process. This involves some breaking changes, so it's also necessary in case we will need additional features from the library in the future.

### Describe the solution you'd like

- Upgrade version
- Make necessary changes according to migration docs [here](https://github.com/Lombiq/UI-Testing-Toolbox/pull/186).
- Review updated OC testing docs [here](https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/TestableOrchardCoreApps.md).

[Jira issue](https://lombiq.atlassian.net/browse/OCC-102)

**Comment by DemeSzabolcs** [comment]
@DAud-IcI What do you think about migrating to the new .NET 6.0 [hosting model](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#new-hosting-model), in this issue? We already use this in other projects (example: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/src/Lombiq.OSOCE.Web/Program.cs). I have to do things in `Program.cs` anyway, so this could be a good opportunity.

**Comment by DAud-IcI** [comment]
I'm in favor of it.
