### ISSUE TITLE
Some sort of loading sign feedback when clicking pay button (OCC-103)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#213]
### Is your feature request related to a problem? Please describe

It would be nice to have some sort of feedback when you click on pay on the checkout page, that it is loading/processing the payment.

### Describe the solution you'd like

A moving loading circle in the Pay button, while it also gets disabled.

### Describe alternatives you've considered

A loading sign in the middle of the screen while the background is blurred.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-103)

**Comment by DemeSzabolcs** [comment]
> A moving loading circle in the Pay button, while it also gets disabled.

I think it's already disabled, but it has the hover styling regardless. So yes, that needs to be corrected.

**Comment by wAsnk** [comment]
Oh and one more thing, that I forgot to mention. Is it possible to use a default bootstrap button style (`btn btn-success`) instead of this custom one? Or that is not related to OCC?

**Comment by wAsnk** [comment]
Yeah, ofc you can override it with CSS. I'm just curious why is that a custom button when there are nice buttons already in bootstrap. 😄

**Comment by DemeSzabolcs** [comment]
> I'm just curious why is that a custom button when there are nice buttons already in bootstrap. 
Oh okay, sorry. There is no reason, this is from the Stripe integration, and I didn't care about the styling when I did that, but you are right.

**Comment by wAsnk** [comment]
There is no need to say sorry, don't worry, I'm just asking. No harm was done😄
