### ISSUE TITLE
Hide Stripe API secret input value on settings page (OCC-112)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#229]
### Is your feature request related to a problem? Please describe

Hide the secret key input field value on Stripe API settings page so it is not shown directly on the page load.

### Describe the solution you'd like

Set the input type to password. And add hint to explain the workflow.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-112)

**Comment by DemeSzabolcs** [comment]
What do you mean by:

> And add hint to explain the workflow.

What should we explain exactly?

**Comment by wAsnk** [comment]
That the password won't be shown after save. Or something that explains why the input field is empty after a save and it's saved, but for security reasons it is not shown. Or at least that's what I experienced when I set the type to password, but correct me if that's not how it should work.
