### ISSUE TITLE
Build issue (OCC-116)

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore.Commerce#235]
Hi,

I have just checked out dev branch and tried to build with VS 2022.
Build failed with errors below.

Any idea?

the directory parameter marked bold below seems strange - there is a space after f: (before \\).

Thanks,
Dieter

8>Calling pnpm install in F:\daten\Documents\d\dev_orchard_core_neu\OrchardCoreCommerce-Test1\src\OrchardCore.Commerce.Web:
8>Already up-to-date
8>
8>
8>> nodejs-extensions@0.0.1 lint:markdown:args F:\daten\Documents\d\dev_orchard_core_neu\OrchardCoreCommerce-Test1\src\OrchardCore.Commerce.Web\node_modules\.nx
8>EXEC : > node scripts/lint-markdown.js $npm_config_directory || AREA=markdown STEP=linting pnpm error "--directory=**F: \\daten\\Documents\\d\\dev_orchard_core_neu\\OrchardCoreCommerce-Test1\\**"
8>
8>Unbound variable "npm_config_directory"
8>
8>EXEC : > nodejs-extensions@0.0.1 error F: \daten\Documents\d\dev_orchard_core_neu\OrchardCoreCommerce-Test1\src\OrchardCore.Commerce.Web\node_modules\.nx
8>> echo "Error in $AREA pipeline: $STEP failed." "--directory=F:\\daten\\Documents\\d\\dev_orchard_core_neu\\OrchardCoreCommerce-Test1\\"
8>
8>Error in markdown pipeline: linting failed. --directory=F:\daten\Documents\d\dev_orchard_core_neu\OrchardCoreCommerce-Test1\
8>C:\Users\Didi\.nuget\packages\lombiq.nodejs.extensions\1.0.0-alpha.occ-15.3\Lombiq.NodeJs.Extensions.targets(219,5): error MSB3073: Der Befehl "pnpm lint:markdown:args --directory=F:\daten\Documents\d\dev_orchard_core_neu\OrchardCoreCommerce-Test1\" wurde mit dem Code -1 beendet.
8>Die Erstellung des Projekts "OrchardCore.Commerce.Web.csproj" ist abgeschlossen -- FEHLER.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-116)

**Comment by 0liver** [comment]
Thanks for trying out OCC!

The error you see is a breaking change in `pnpm` between `v6` and `v7`. We're working on fixing this problem, but for now, please use `pnpm@6` for this project. You can use `corepack` to activate the desired version, if your Node.js version supports it.

Regards,
Oliver

**Comment by dpomt** [comment]
> Thanks for trying out OCC!
> 
> The error you see is a breaking change in `pnpm` between `v6` and `v7`. We're working on fixing this problem, but for now, please use `pnpm@6` for this project. You can use `corepack` to activate the desired version, if your Node.js version supports it.
> 
> Regards, Oliver

Thanks a lot Oliver for responding so quick.

I have installed a newer nodejs version and use corepack as suggested:
corepack prepare pnpm@6.32.11 --activate

No more build errors.

Best regards, 
Dieter
