### ISSUE TITLE
Tiered pricing (OCC-119)

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore.Commerce#241]
Hi,

in NwazetCommerce, there was Tiered pricing functionality:

![image](https://user-images.githubusercontent.com/1379660/210268773-b4e7574c-a6db-4c43-a270-5598ac50dd52.png)
![image](https://user-images.githubusercontent.com/1379660/210268825-5705023f-1157-4041-b1d9-256cd2dc7bf5.png)

Are there any plans (and timeline) for this?

Thanks,
Dieter

[Jira issue](https://lombiq.atlassian.net/browse/OCC-119)

**Comment by DAud-IcI** [comment]
Hi, no we haven't considered this yet. Thanks for the suggestion. We are currently evaluating what features are most in demand for future releases so if this issue gains traction we will bump it up on the priority.

**Comment by dpomt** [comment]
Do you have any ideas when this might be implemented?
I am migrating an Orchard 1.x shop website that is based on tiered pricing.

Any idea yet how tiered prieces could conceptually be integrated in OCC?

Thanks.
Dieter
