### ISSUE TITLE
Documentation menu (OCC-128)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#257]
You added some new pages to the documentation recently.

Ex: https://commerce.orchardcore.net/en/latest/features/inventory/

if you want them to appear in the menu, you need to add them to the `nav` section in the mkdocs.yml file.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-128)

**Comment by DAud-IcI** [comment]
Thanks, I assumed the menu came from the directory structure.
I've created a new PR (#258). Could you review it, please?
