### ISSUE TITLE
Migrate the latest Node.js Extensions, update configuration (OCC-131)

### ISSUE THREAD

**Issue by 0liver** [OrchardCMS/OrchardCore.Commerce#261]
### Is your feature request related to a problem? Please describe

There's some obsolete configuration [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj#L8). Let's remove that.

### Describe the solution you'd like

See [https://github.com/Lombiq/Gulp-Extensions/blob/dev/Docs/MigrationToNodeJsExtensions.md (where n](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/Docs/Markdown.md) for how to configure the Markdown pipeline now.

### Describe alternatives you've considered

Gulp Extensions, but looks like that's being [deprecated](https://github.com/Lombiq/Gulp-Extensions#deprecation-notice). 😂

[Jira issue](https://lombiq.atlassian.net/browse/OCC-131)

**Comment by wAsnk** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore.Commerce/pull/270
