### ISSUE TITLE
Global setting to toggle if net or gross prices should be used (OCC-135)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#265]
### Is your feature request related to a problem? Please describe

Currently the prices with tax are displayed in the shopping cart. At least in the USA it's customary to display the net price instead.

**Does this affect the total on the checkout screen too, or just the individual price labels?**

### Describe the solution you'd like

- Add a site setting with editor, just a checkbox and description is enough.
- The setting should change what's displayed in _ShoppingCartCell_OldPrice.cshtml_.
- Search for wherever `.GetGrossPrice()`, `ShoppingCartLineViewModel.UnitPrice` and `ShoppingCartLineViewModel.LinePrice` are used and check if it should be made conditional as well.
- If the total has to be net price too, then the return value of the _~/checkout/price_ API and the values in _ShoppingCartViewModel.Totals_ has to consider this option as well. In this case try to DRY them together.
- The Total line on the Cart page should display net and gross price too.

### Describe alternatives you've considered

We may also display net and gross prices everywhere, but that's quite bloated.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-135)

**Comment by Piedone** [comment]
In the EU VAT system, both prices are needed, since as a private consumer you pay gross prices, as a company or other entity while you pay the gross price, in the end (to simplify a lot) it'll cost you the net price.

**Comment by DAud-IcI** [comment]
I think that's only applicable to the product display, where we already show both (in fact since #255 if there is a discount you can access all four: promo net price, promo gross price, old net price, old gross price). So the webshop developer can hide either by overriding the templates. But you shouldn't need both on summaries, like the tables on the Cart page and Order display.

**Comment by Piedone** [comment]
You don't need both of them every single time indeed, but at least on the product page and the final summary before payment it should be displayed.

**Comment by porgabi** [comment]
1. If tax rate is provided, the Product page already shows both prices. I assume there's no changes needed to this:
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/293697f8-606c-4943-abb1-0cc859cdd93c)

2. PriceVariantProducts don't have tax rate properties, so if I understand correctly, this is not applicable to them. 
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/79348b2d-64f0-46c7-821d-59081aa5e763)

3. The Cart page's Total line needs to show Net and Gross prices. Right now, the way it works is the relevant column either display Gross Price (if it's provided on the Product) or simply Price (if Gross price isn't specified).
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/5856a534-2d64-4758-8721-0a9d79b358b9)
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/339546a7-113b-481d-a83d-d0fab31ff9a6)
To show both prices when applicable, should another column be added conditionally, or should it only be displayed in the text within the Total row? The latter would be something like this:
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/fbc1630c-4f9a-4613-b3e6-501caf0cd50d)

**Comment by DAud-IcI** [comment]
1. Nothing to do here, the webshop developer can hide either fields by overriding the templates.
2. Yes, it can be ignored for now.
3. The `TaxShoppingCartEvents.DisplayingAsync()` method updates the table headers by replacing the "Price" header with "Gross Price". The cells are populated by `ShoppingCartController.Index()` using the "ShoppingCartCell_{headerName}.cshtml" shape (so ShoppingCartCell_Price.cshtml and ShoppingCartCell_GrossPrice.cshtml). You can change header updating logic in the event handler, to check the site setting and then leave the headers alone, do the substitution as it's done now, or insert the new column instead. The total is fine as you displayed, maybe place a separator (such as a [fullwidth vertical line](https://www.compart.com/en/unicode/U+FF5C)) between the net and gross if both are displayed.
