### ISSUE TITLE
Global Discounts: permision (OCC-136)

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore.Commerce#267]
Hi,

first, thanks a lot for implementing the Global Discounts!!

I have tested the functionality. It works fine :)

Just one small thing:

In https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/docs/features/promotions.md it's written that permission List content item(s) owned by all users"  has to be allowed. 
But in implementation, check is done against CommonPermissions.PreviewContent

Either documentation or implementation should be adapted.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-136)

**Comment by DAud-IcI** [comment]
Thanks! The documentation was correct, it was supposed to be the ListContent.
