### ISSUE TITLE
Product Sku localization (OCC-139)

### ISSUE THREAD

**Issue by havana7** [OrchardCMS/OrchardCore.Commerce#271]
Each localized product must have its own Sku. This means that you need to have different skus for the same products.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-139)

**Comment by DAud-IcI** [comment]
The Jira issue is simply a link for internal tracking. It doesn't contain any issue details.

**Comment by hishamco** [comment]
I might dig into that

**Comment by MatteoPiovanelli-Laser** [comment]
hello.
In O1 we solved this by having providers to handle exceptions to the rule "the SKU must be unique" for those cases where different ContentItems are different representations of the same product.
It's the implementations of https://github.com/LaserSrl/Nwazet.Commerce/blob/Laser/Services/ISKUUniquenessHelper.cs

**Comment by DAud-IcI** [comment]
I agree, exception handling providers is a good solution specifically for the problem of SKU clashes. But it doesn't sit well with me that a separate content item has to be created for localization in the first place. It means that prices, discounts and stocks are separate for what is ostensibly the same product. It also complicates SKU -> content item look-ups too.
