### ISSUE TITLE
Commerce-friendly base template

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore.Commerce#28]
http://bootstrap-ecommerce.com/
I found this website where most of the different layout elements are already composed with Bootstrap 4.

**Comment by bleroy** [comment]
Lovely, thanks. So how should we integrate that? As part of the base package, or as part of a sample?

**Comment by jeffolmstead** [comment]
Do you know the license on it? I cannot seem to find it anywhere. If we want to stay MIT (or equivalent) then that would be a consideration.

**Comment by bleroy** [comment]
You're right, I assumed it was the same as Bootstrap, but it's not. How about we change the title of this issue?

**Comment by Skrypt** [comment]
I've not found any licence in his code. Free as beer.

**Comment by Allann** [comment]
http://bootstrap-ecommerce.com/doc.html#license
