### ISSUE TITLE
Workflow event won't be triggered if only webhook is used (OCC-149)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#284]
### Describe the bug

OrderCreatedEvent workflow is only triggered in FinalModificationAsync(), which is called only in the PaymentConfirmationMiddleware(), thus when only the WebhookController is used for the confirmation, the workflow won't be triggered.

### To Reproduce

I've got no real repro ready, this is only a logical observation.

### Expected behavior

When an OrderPart Status is set to Ordered when it was something else before then trigger the workflow.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-149)

**Comment by DemeSzabolcs** [comment]
> When an OrderPart Status is set to Ordered when it was something else before then trigger the workflow.

We did that back in the early days, and for some custom reason that I can't recall, we had to implement the custom `OrderCreatedEvent`. However I think this could be easily fixed by also triggering the event in the webhook.
