### ISSUE TITLE
Publish to NuGet step fails in publish workflow (OCC-152)

### ISSUE THREAD

**Issue by DemeSzabolcs** [OrchardCMS/OrchardCore.Commerce#286]
### Describe the bug

Publish to NuGet step fails in publish workflow. See:
https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/4630911422/jobs/8193114176

### To Reproduce

Merge a PR, or trigger the workflow.

### Expected behavior

The publish workflow and the "Publish to NuGet" step inside it shouldn't fail.

### Screenshots

[Jira issue](https://lombiq.atlassian.net/browse/OCC-152)

**Comment by DAud-IcI** [comment]
```
dotnet pack failed for the project /home/runner/work/OrchardCore.Commerce/OrchardCore.Commerce/src/OrchardCore.Commerce.Web/OrchardCore.Commerce.Web.csproj.
```

wtf, why is it trying to pack the startup project?!
