### ISSUE TITLE
ExecWithMutex (OCC-155)

### ISSUE THREAD

**Issue by PabloSergi** [OrchardCMS/OrchardCore.Commerce#291]
Hi guys. I am learning c# not so long ago. Sorry if this is a beginner's question, but I seem to have read everything carefully and searched the internet for a long time, but haven't found anything about my problem. I'm learning c# on my m1 mac and don't have an update to the latest version at the moment. Decided to try creating an online store today, downloaded OrchardCore and OrchardCore.Commerce. The first one works, the second one gives the following error. 

/Users/pablo_sergi/.nuget/packages/lombiq.nodejs.extensions/1.2.2/Lombiq.NodeJs.Extensions.targets(5,5): Error MSB4216: Could not run the "ExecWithMutex" task because MSBuild could not create or connect to a task host with runtime "NET" and architecture "arm64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "MSBuild.exe" exists and can be run. (MSB4216) (OrchardCore.Commerce)

I updated nuget, the error remains. Not quite sure what to do about it. It seems to be a lombiq.nodejs.extensions compatibility issue? How do I fix this in general? 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-155)

**Comment by 0liver** [comment]
This is a problem within Node.js Extensions and has been reported there: https://github.com/Lombiq/NodeJs-Extensions/issues/45.

@DAud-IcI Should we close this one here or not?

**Comment by DAud-IcI** [comment]
Let's keep it open for now. I've marked blocker relationship in the corresponding Jira issues. If https://github.com/Lombiq/NodeJs-Extensions/issues/45 involves a fix then it has to be published to NuGet and then the package reference updated here.

**Comment by Piedone** [comment]
An update to NE v1.2.3 fixes this.
