### ISSUE TITLE
Unable to publish to NuGet proper (OCC-148)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#293]
### Describe the bug

While trying to publish a release, pushing to [the NuGet package ](https://www.nuget.org/packages/OrchardCore.Commerce) via https://www.nuget.org/api/v2/package/ fails with
`403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)` 
(see failed run [here](https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/4716326555/jobs/8363950747#step:4:3990))

### To Reproduce

Steps to reproduce the behavior: create a release version tag (e.g. `v1.1.0`) or restart the action linked above.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-148)

**Comment by DAud-IcI** [comment]
@sebastienros is it possible that [the key you put into the `NUGET_API_KEY` secret](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/42#issuecomment-1216809957) is actually expired? If yes, can you please update it?

**Comment by sebastienros** [comment]
Yes, I regenerated it for OC on Friday due to other failures. Will update it. I will create a separate one such that one doesn't break the other.
