### ISSUE TITLE
Minimum viable product (MVP) features (OCC-61)

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/OrchardCore.Commerce#3]
The work will focus at first on porting a minimum viable feature set:

* [Product, price, and inventory parts and/or fields](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/5) (those were a single part in Nwazet)
  Note: not all products have a price
* [Shopping cart](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/15)
* [Checkout](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/16) (probably redesigned around Orchard Workflows)
* [Base infrastructure for payment](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/17), plus one implementation (Stripe)
* [Order content type and management screens](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/18) (including a redesign and refactoring of the order part)
* Workflow activities for most of the above
* [Shipping infrastructure and default implementation](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/4)
* [Tax infrastructure and default implementation](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/33)

Globalization should be taken into account at every step.

This issue exists so we can discuss what features should go into the minimum feature set that we build first. Discussion of the design of each of the features should happen in their respective issues (links above). 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-61)

**Comment by DrewBrasher** [comment]
I would be happy to help with this if there is anything you want me to work on.

**Comment by bleroy** [comment]
Hi @DrewBrasher ! Sorry for the delay. There's a number of things that would be good contributions at this point in time, depending what you're interested in. Starting shipping and/or tax are good ones. Implementing them entirely can be a huge amount of work, but implementing the default minimal implementation is very manageable. Another thing is the order management screen. It exists, but is very rough, so if you're interested in making things nice and useable, that can be a good one. Cheers!

**Comment by DrewBrasher** [comment]
@bleroy I will start with the order management.

**Comment by bleroy** [comment]
If all your products have a price, that's fine, you can enforce that.

Amount has nothing to do with Azure. What makes you think it does? the type is defined here: https://github.com/OrchardCMS/OrchardCore.Commerce/blob/efd0e30f42e9c3160804a50c880b1929b30020e7/MoneyDataType/Amount.cs

**Comment by mwpowellhtx** [comment]
> Amount has nothing to do with Azure. What makes you think it does? the type is defined [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/efd0e30f42e9c3160804a50c880b1929b30020e7/MoneyDataType/Amount.cs).

Ah okay, I did not see that. I did however find `Amount` in the _Microsoft Azure_ docs, funnily enough in a `Billing` namespace.

**Comment by bleroy** [comment]
As for your original question, the records-based approach was just Orchard's content model. OC is document-based, so has no use for records. If you wanted to migrate from one to the other, that wouldn't be specific to Commerce, and as far as I know there wasn't a goal for back-compat, so your best bet is probably to go through export and import.

**Comment by mwpowellhtx** [comment]
> As for your original question, the records-based approach was just Orchard's content model. OC is document-based, so has no use for records.

My experience with document databases is valuable here, especially potentially decoupling detail records from parent records, for scalability, performance reasons, at least coming from a _MartenDB_. Interested to learn and do more vis-a-vis _OC_, _Commerce_, where that is concerned.

> If you wanted to migrate from one to the other, that wouldn't be specific to Commerce, and as far as I know there wasn't a goal for back-compat, so your best bet is probably to go through export and import.

Not to be misconstrued or anything. Our starting point is _OC_, not _Orchard_, or _Orchard Commerce_. `Commerce` migration paths, ports, etc, are my interest here.

Are y'all conducting meetings to kick off and pull things forward over this project?

**Comment by bleroy** [comment]
Orchard Core has an import feature, so as long as you can build a file in the format it takes, you should be able to import anything. I'd ask about that on an Orchard Core forum.
We're not conducting meetings specifically for this commerce project, no. There are two weekly meetings for Orchard Core though.

**Comment by mwpowellhtx** [comment]
> Orchard Core has an import feature, so as long as you can build a file in the format it takes, you should be able to import anything. I'd ask about that on an Orchard Core forum.

As I said, we are not starting from _Orchard_, or _Orchard Commerce_. We are launching a brand new _OC_ based site, _Commerce_ enabled is our goal. Anyway, transit the welcome discussion for on-boarding alignment purposes. Let me know what the protocols are for picking up on issues, contributing, etc.

Thanks...

**Comment by mwpowellhtx** [comment]
> In any case, first step would be to describe the design you'd like to go for so we can check it's inline with the goals and design principles of the project.

Key statement there, yes. That's the sort of engagement, conversation, we'd **_all_** benefit from.

**Comment by mwpowellhtx** [comment]
Scanning through the MVP feature set... A bit confused how far along things really are. Especially given the timeliness of some of the comments, 1, 2, 3+ years aged at this point. Scale of 1-10 readiness, about a 3? 3.5? Are the efforts parked on branches? Someone's local and/or github repo, branch, etc? Thank you...

**Comment by bleroy** [comment]
Product catalog and shopping cart are done and that's about it. I'm not currently writing code for the project. I'll let others chime in if they are. Anyone who wants to use this project should be ready to fill in the holes themselves.

**Comment by DrewBrasher** [comment]
I'm not right now but I'm still interested in helping. I decided I needed more experience in Orchard Core before I started trying to help but I'm just finishing up a project that used Orchard Core CMS so I'm planning to try to start helping with this soon.

**Comment by DAud-IcI** [comment]
Please check out the latest news on the MVP in this discussion thread: [Survey Results and MVP](https://github.com/OrchardCMS/OrchardCore.Commerce/discussions/142)

**Comment by Piedone** [comment]
Shouldn't this be closed now, with the MVP having been shipped?

**Comment by DAud-IcI** [comment]
Good point, this can be closed. ([see announcement](https://github.com/OrchardCMS/OrchardCore.Commerce/discussions/260))
