### ISSUE TITLE
Handle taxes differently for corporations and private individuals. (OCC-162)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#301]
### Is your feature request related to a problem? Please describe

In some cases they are taxed differently, e.g. the corporation doesn't have to pay VAT for certain regions.

### Describe the solution you'd like

Add a checkbox to checkout for corporation. Also VAT number.

### Describe alternatives you've considered

Not sure, let's discuss!

[Jira issue](https://lombiq.atlassian.net/browse/OCC-162)

**Comment by porgabi** [comment]
So, on the Checkout page, there needs to be a "Corporation" checkbox, that part seems clear enough. However, what exactly should ticking it affect?

**Comment by porgabi** [comment]
1. 
> The value of the checkbox during checkout should be added to `PromotionAndTaxProviderContext`

So the `IsCorporation` bool (i.e. the checkbox on Checkout) is to be used based on the value of the new enum site setting.
- If the setting is set to `Checked`, examine the value of the `IsCorporation` bool, and if it is set to true, do not match tax rates.
- If the setting is set to `Unchecked`, examine the value of the `IsCorporation` bool, and if it is set to false, match tax rates as usual.
- If the setting is set to `Ignore`, don't look at the `IsCorporation` bool, and match tax rates as usual.

I'm certain I got this wrong. Please elaborate, for I am confusion.

2.
> Same for the VAT number text field

Other than adding this to `PromotionAndTaxProviderContext` as well, is it to be somehow used for matching in `TaxRateTaxProvider` too? Or anywhere else?

**Comment by DAud-IcI** [comment]
1. Sorry, I think I did a bad job at describing the idea. You should have one enum for each tax rate row, in other words put it into the `TaxRateSetting` class. Then when matching the tax rates check its value [along with the rest of the `TaxRateSetting` properties](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/1272a878c386fc5b7310e1ca70d2f59bed97901c/src/Modules/OrchardCore.Commerce/Services/TaxRateTaxProvider.cs#L71-L77):
  - If the `TaxRateSetting.IsCorporation` is set to Checked, match the tax rate if `PromotionAndTaxProviderContext.IsCorporation == true` and the other conditions match too.
  - If the `TaxRateSetting.IsCorporation` is set to Unchecked, match the tax rate if `PromotionAndTaxProviderContext.IsCorporation == false` and the other conditions match too.
  - If the `TaxRateSetting.IsCorporation` is set to Ignored, match the tax rate if the other conditions match.

2. Add a string property to the `TaxRateSetting` class. Since this is just another text field you can use the `IsMatchingOrEmptyPattern` method in `TaxRateTaxProvider.MatchTaxRate` to check it just like e.g. `taxCode` is done there.

Add two new columns in `TaxRateSettings_Edit.cshtml` for these two new `TaxRateSetting` properties and update `TaxRateSettingsDisplayDriver`. If it's still not clear, ping me and let's have a call.
