### ISSUE TITLE
Mention project in the OC docs (OCC-167)

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore.Commerce#306]
### Is your feature request related to a problem? Please describe

Apart from the https://docs.orchardcore.net/en/latest/docs/resources/owners/ page, this project is not mentioned in the official OC docs anywhere. For better visibility, I think it should be added.

### Describe the solution you'd like

The best would perhaps be a how-to guide about creating simple webshop: https://docs.orchardcore.net/en/latest/docs/guides/. The project could also be mentioned and linked from other pages, perhaps under [Status](https://docs.orchardcore.net/en/latest/#status) (that OCC is not technically part of OC part still an official suite of extensions) and [Reference](https://docs.orchardcore.net/en/latest/docs/reference/).

Also, it could be added to the Portfolio section and perhaps Features one too on the website.

### Describe alternatives you've considered

Keeping the project all to myself :D.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-167)

**Comment by Piedone** [comment]
@DAud-IcI can you address this sooner rather than later?

**Comment by porgabi** [comment]
I'm on a bit of a documentation streak right now, so might as well jump on this one as well. Do you have any additional thoughts on the matter, @DAud-IcI?

**Comment by DAud-IcI** [comment]
I'd appreciate that. If you want you can refer to [the presentation I did on Orchard Harvest](https://www.youtube.com/watch?v=SQHVUUUT8O0&list=PLpCsCyd254Fr-2gbJEOLAJaoU_4EqHKaI&index=6).

**Comment by Piedone** [comment]
Ah yes, do include that video too
