### ISSUE TITLE
Configure Auto Setup (OCC-171)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#319]
### Is your feature request related to a problem? Please describe

It's tiresome to manually go through the site setup after each time it's reset.

### Describe the solution you'd like

Add [auto setup](https://docs.orchardcore.net/en/latest/docs/reference/modules/AutoSetup/) for the default tenant to the development appsettings file. It should use the `OrchardCore.Commerce.Development.Setup` recipe.

### Describe alternatives you've considered

I have nothing.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-171)

**Comment by Piedone** [comment]
Is this really only about running the existing recipe with Auto Setup? (Because that's almost trivial.)

**Comment by DAud-IcI** [comment]
I think so, and I agree.

**Comment by Piedone** [comment]
Is "Orchard Core Commerce - Custom Tax Rates" deliberately not enabled in the Development recipe?

**Comment by DAud-IcI** [comment]
Yes, you'd only enable that if you actually want to have a [locally maintained tax rate table](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/docs/features/taxation.md#locally-maintained-tax-rates). Currently enabling it wouldn't cause problems, but in the future once [third party tax service](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/159) is implemented these two will be conflicting because both features will serve the same purpose just using different data sources.

**Comment by Piedone** [comment]
I see, thanks.
