### ISSUE TITLE
Check 'Maximum Order Quantity' update on Cart (OCC-183)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#340]
When I want to add a discounted product that has a 'Maximum Order Quantity' = 2 an set 3 items, I get the expected message:
`The checkout quantity for Test Discounted Product is more than the maximum allowed.`

But when I am on the cart page and change the number of items to a number > 3, there is no such message so I could order more than 'Maximum Order Quantity' limit that is set.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-183)

**Comment by DAud-IcI** [comment]
Sorry, I wasn't able to reproduce this. Can you send a step-by-step or screen recording?

**Comment by porgabi** [comment]
Not OP, but I could reproduce by simply adding 1 Test Discounted Product to cart and then, within the cart, updating its quantity to 5, which shouldn't be possible as the max order quantity is set to 2.

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/cf8b1123-4269-4b56-ae60-166dd1160b3a)

**Comment by DAud-IcI** [comment]
That won't actually allow you to order more than the maximum though.

**Comment by porgabi** [comment]
I haven't encountered any errors while checking out with these parameters, so it seems possible:

https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/12214475-aa08-4f78-b044-f163c81f7288

**Comment by porgabi** [comment]
Additionally, if you check out with a quantity higher than the available inventory's value with back ordering disabled, you get a big friendly exception.

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/757248d6-c923-4dc3-a99a-0e88f8f74bd1)

I think it just needs inventory checking added for the method that handles cart updating.
