### ISSUE TITLE
Releases in documentation (OCC-184)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#342]
The latest release in the docs is 1.1.0.

You could add the recent missing ones and add a step in your Release process to create the related .md file in order to not forget it.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-184)

**Comment by Piedone** [comment]
How about just keeping release notes on GitHub, under Releases?

**Comment by agriffard** [comment]
That is a good solution if you want get the releases in only one place.
Then, I suggest to get rid of the releases section in the docs, in order to not have an out of date list of releases.
