### ISSUE TITLE
Documentation: Parts and Fields (OCC-189)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#348]
Make a documentation page for each kind of available part and field provided by the module:

- Product
- Price
- PriceVariants

and attributes:

- Boolean
- Numeric
- Text

Describe what it does but show also examples of Admin and front UI. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-189)

**Comment by porgabi** [comment]
A page, as in a Markdown page within the repository ([these do exist](https://github.com/OrchardCMS/OrchardCore.Commerce/tree/main/docs) already but could be extended), or a dedicated demo page within the application itself?
cc @DAud-IcI

**Comment by agriffard** [comment]
The current page is https://commerce.orchardcore.net/en/latest/features/products-and-prices/

A Markdown page per feature with screenshots could be interesting.

**Comment by porgabi** [comment]
Looking to test the new pages on the documentation site itself, which seems to require creating a separate version for the branch. As far as I can tell, this is not something I have permissions for, could you create one for the `issue/OCC-189` branch?

**Comment by agriffard** [comment]
You can test it locally:
https://docs.orchardcore.net/en/latest/docs/topics/docs-contributions/#running-the-documentation-site-locally

**Comment by agriffard** [comment]
I built it and you can see the result here:
https://commerce.orchardcore.net/en/issue-occ-189/features/product-part/

**Comment by porgabi** [comment]
Thanks!
