### ISSUE TITLE
Upgrade to Orchard Core 2.0 once it's released and remove Newtonsoft.Json from the code base (OCC-194)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore.Commerce#362]
Orchard Core 2.0 will finally migrate to System.Text.Json and [drop Newtonsoft.Json support](https://github.com/OrchardCMS/OrchardCore/blob/main/src/docs/releases/1.9.0.md#drop-newtonsoftjson-support). This much anticipated event should be followed up in Orchard Core Commerce as well.

Blocking:
- OC 2.0 release (couldn't find a release issue in the OC repo)
- https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/709

----

Obsolete description:

### Is your feature request related to a problem? Please describe

Currently OCC has serialization via Newtonsoft Json.NET and System.Text.Json. Both are actually used in different places. This makes things unnecessarily complicated as serializers have to be implemented in two different frameworks.

### Describe the solution you'd like

Orchard Core still uses Json.NET at the core of its content system ([see](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentElement.cs#L31)) and so do many other third party modules and libraries that build on OC. While the OC team has expressed intent to eventually switch over to STJ, this is not in the near future. Additionally based on previous comments (for example [here](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/53#issuecomment-586467524)) we might want to rewrite the STJ implementation from scratch if this ever happens.
In the meantime, we should do the following to make the code more maintainable and approachable:
- Remove the STJ converters
- If possible, rename the Json.NET converters without the "Legacy" prefix. (if OC ever changes over to STJ we will delete these converters anyway so I don't expect that we should ever have two different sets.
- Partially rewrite `ShoppingCartSerializer`, `IProductAttributeProvider` and any other file where `using System.Text.Json;` is found to use Json.NET instead.

### Describe alternatives you've considered

Alternatively we may fully commit to STJ-only, but I think at this point this would be premature, an enormous technical debt and a source of future headaches.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-194)

**Comment by hishamco** [comment]
Orchard Core is still using Newtonsoft Json.NET because of YesSQL but for sure if all the JSON stuff is implemented in STJ then the STJ wins

IMHO we could use STJ all over places if all agree

I might have a look to related issue in YesSQL to use STJ

**Comment by DAud-IcI** [comment]
Is there an open issue tracking the transition from Json.NET to STJ in Orchard Core? I can't find one, that's the main reason why I assumed it's off in the far future. I found an open YesSql issue for moving to STJ (https://github.com/sebastienros/yessql/issues/227), but it hasn't been touched since 2020.

If we can get the move to STJ started for YesSQL and OC then I'm all for it (and would like to get involved). But if it will be stuck in limbo for much longer then I'd still prefer to cut down on duplicate code in the meantime.

**Comment by hishamco** [comment]
I might check that issue again, so for now I think we can go with STJ if you don't mind or we will rid off STJ until we finish all the things in YesSQL

**Comment by infofromca** [comment]
Be careful, in my practice, not all kind of data would be processed by STJ easily.  IMO, just keep using Newton, at least for  a while. do not waste time to to modify the not high priority issues . after all the stuff of this project are ok, then consider transfer to STJ
