### ISSUE TITLE
Boolean product attributes not stored in the order screen. (OCC-195)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#365]
### Describe the bug

The Boolean Product Attribute Field is kind of broken, see symptoms below.

### To Reproduce

1. Edit the "Product" content type (or create a new content type with ProductPart and PricePart).
2. Click _Add Field_ and select _Boolean Product Attribute Field_.
3. Order any Product (e.g. https://localhost:5001/testproduct) without ticking the new checkbox.
4. **In the cart there is no attribute indicator below the product name.**
5. Purchase succeeds, but **the Attributes column is empty** both in Order display and editor.
6. Order the same Product again, but this time check the box.
7. On the cart screen it doesn't show the product
8. Trying to click the Pay button **results in this async error** notification:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'OrchardCore.Commerce.ProductAttributeValues.BooleanProductAttributeValue' does not contain a definition for 'PredefinedValue' at CallSite.Target(Closure , CallSite , Object ) at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) at OrchardCore.Commerce.Models.ShoppingCartItem.<>c.<CreateOrderLineFromShoppingCartItemAsync>b__22_1(IProductAttributeValue value) in E:\Repositories\orchard-core\OrchardCore.Commerce\src\Modules\OrchardCore.Commerce\Models\ShoppingCartItem.cs:line 127 
```

### Expected behavior

- The attribute should be applied even if its value is false.
- When displaying attributes in the cart or the order view/editor it should display the Boolean attribute in the `{fieldLabel ?? fieldName}: {Yes/No}` format. For example: `Deluxe Version: Yes` or `Insurance: No`
- Including a boolean attribute shouldn't during checkout.
- Boolean attributes should be displayed and editable in the order editor.

If it helps, this attribute type should be considered as if it was predefined with `true` and `false` possible values. It may benefit to have a container value derived from `IPredefinedValuesProductAttributeValue<bool>` similar to `TextProductAttributeValue` for text attributes.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-195)

**Comment by porgabi** [comment]
> Boolean attributes should be displayed and editable in the order editor.

I assume it'd make sense to handle numeric attributes the same way too, so I'll add that in this one as well. Let me know if I shouldn't, though.
