### ISSUE TITLE
Cloudsmith publishing is broken (OCC-197)

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore.Commerce#369]
### Describe the bug

See the latest workflow runs: https://github.com/OrchardCMS/OrchardCore.Commerce/actions/workflows/publish-cloudsmith.yml

### To Reproduce

This started with the https://github.com/OrchardCMS/OrchardCore.Commerce/commit/b63eae4f4e0470bbce487b9c59a17ad0a1df620e commit.

### Expected behavior

Cloudsmith publishing finishes without errors.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-197)

**Comment by DAud-IcI** [comment]
Works now, e.g. https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/6597925815
