### ISSUE TITLE
Upgrade to Orchard Core 1.8 (OCC-223)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore.Commerce#411]
After https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/638 is completed, upgrade OCC to Orchard Core 1.8.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-223)

**Comment by Psichorex** [comment]
@sarahelsaig Is this html intentionally written this way?
After OC 1.8 this is raising a duplicate form control name html validation error. Shall we ignore or address?
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/92299130/2ffbbbb4-b9e6-40dd-aa55-0b97a858e638)

**Comment by Psichorex** [comment]
Say this to my HtmlValidationReport.txt!!!!
[HtmlValidationReport.txt](https://github.com/OrchardCMS/OrchardCore.Commerce/files/14374842/HtmlValidationReport.txt)

**Comment by Psichorex** [comment]
Well by the way it seems that the CI is only failing due this test : https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/8005597326?pr=412

And this one failed in OSOCE for me but passed on CI so it really seems to be a flaky one.

**Comment by sarahelsaig** [comment]
It's trying to copy the inherited version from UITT and the one in the test project, some race condition may be at play.

**Comment by Psichorex** [comment]
I was missing the UITT and TT nuget package updates in the Commerce solution but after upgrading them the test still fails.
What exactly do you mean by the inherited vs test project version? Isn't it only using our module from NuGet?

**Comment by Psichorex** [comment]
Oh it's clear now. This is only happening locally by the way so in theory this is not ruining the CI builds.

**Comment by sarahelsaig** [comment]
Ok, feel free to ignore here if it works in CI. But please open a bug issue in https://github.com/Lombiq/UI-Testing-Toolbox/.

**Comment by Piedone** [comment]
You need to use `Content` on the file here too. But you can create a file named differently too: https://github.com/Lombiq/UI-Testing-Toolbox/blob/94f57ee63781e832d2f332eea7bdc19f3fac6ac4/Lombiq.Tests.UI/Docs/Configuration.md#html-validation-configuration

**Comment by Piedone** [comment]
I don't really see my above comment addressed. Having flakyness in the test project is not good.

**Comment by sarahelsaig** [comment]
It's not actually flaky, it works reliably in CI. Also it's not specific to OCC. Like I said, a UITT issue should be opened.

**Comment by Piedone** [comment]
But it's not an issue as I explained above.
