### ISSUE TITLE
Suggestion:  Don't use float/double in constructors

### ISSUE THREAD

**Issue by Allann** [OrchardCMS/OrchardCore.Commerce#43]
I really like the Amount class, however you will soon find you get rounding issues if you use float and double casting in the amount constructor.  I would suggest you always only accept decimal types.

[Money.zip](https://github.com/OrchardCMS/OrchardCore.Commerce/files/3792014/Money.zip)

I created a money datatype a while back I thought I'd share as I did the currency slightly differently which you might want to have a look at.  This technique doesn't require specific currency types but instead leverages culture/region info built into .Net standard.

I'd be interested in helping out if you'd like my help.

Here are the tests for the above project if needed.

[MoneyFacts.zip](https://github.com/OrchardCMS/OrchardCore.Commerce/files/3792025/MoneyFacts.zip)

**Comment by bleroy** [comment]
Good point. Happy to take pull requests! Thanks!

**Comment by Allann** [comment]
I have been building the solution for this and extended it a fair amount.  I'll add the pull request soon.

**Comment by Allann** [comment]
There is an issue which was found by the EnsureCurrencyAddsRealCurrencyForCodeThatExists test.  Since multiple providers can contain the same ISOCode the potential is that the EnsureCurrency call will actually fetch the wrong one.
For example, if the default provider has 'AMD' and a test provider also had 'AMD' there is no code to prevent this from happening.
The test assumes the first does not have that as it is requesting the TestProvider instance.  

Does that make sense?

Was it your intention to allow the ISO currencies to be overridden with 'user values'? I understand adding instances that are not recognised, like SixPence, but I don't understand overriding defaults.  When I use AUD, I expect it to be the default Australian Dollar currency.

**Comment by bleroy** [comment]
A currency is like a culture: if it has the same code, it's the same, and its data should be the same as well. Overriding defaults with user data doesn't make sense.

**Comment by Allann** [comment]
that is my point.  I can checkin and push my branch if you want to review.  I have included a "KnownCurrencyTable" that is built from a combination of Culture and Region Info objects built into NetStandard 2.0.  The produced list is below:
```
United Arab Emirates Dirham - AED, د.إ.‏, 2
Afghan Afghani - AFN, ؋, 2
Albanian Lek - ALL, Lekë, 0
Armenian Dram - AMD, ֏, 2
Argentine Peso - ARS, $, 2
Australian Dollar - AUD, $, 2
Azerbaijani Manat - AZN, ₼, 2
Bosnia-Herzegovina Convertible Mark - BAM, КМ, 2
Bangladeshi Taka - BDT, ৳, 2
Bulgarian Lev - BGN, лв., 2
Bahraini Dinar - BHD, د.ب.‏, 3
Brunei Dollar - BND, $, 2
Bolivian Boliviano - BOB, Bs, 2
Brazilian Real - BRL, R$, 2
BitCoin - BTC, ₿, 8
Bhutanese Ngultrum - BTN, Nu., 2
Botswanan Pula - BWP, P, 2
Belarusian Ruble - BYN, Br, 2
Belize Dollar - BZD, $, 2
Canadian Dollar - CAD, $, 2
Congolese Franc - CDF, FC, 2
Swiss Franc - CHF, CHF, 2
Chilean Peso - CLP, $, 2
Chinese Yuan - CNY, ¥, 2
Colombian Peso - COP, $, 0
Costa Rican Colón - CRC, ₡, 2
Cuban Peso - CUP, $, 2
Czech Koruna - CZK, Kč, 2
Danish Krone - DKK, kr., 2
Dominican Peso - DOP, $, 2
Algerian Dinar - DZD, د.ج.‏, 2
Egyptian Pound - EGP, ج.م.‏, 2
Eritrean Nakfa - ERN, Nfk, 2
Ethiopian Birr - ETB, Br, 0
Euro - EUR, €, 2
British Pound - GBP, £, 2
Georgian Lari - GEL, ₾, 2
Guatemalan Quetzal - GTQ, Q, 2
Hong Kong Dollar - HKD, $, 2
Honduran Lempira - HNL, L, 2
Croatian Kuna - HRK, kn, 2
Haitian Gourde - HTG, G, 2
Hungarian Forint - HUF, Ft, 2
Indonesian Rupiah - IDR, Rp, 0
Israeli New Shekel - ILS, ₪, 2
Indian Rupee - INR, ₹, 2
Iraqi Dinar - IQD, د.ع.‏, 2
Iranian Rial - IRR, ريال, 2
Icelandic Króna - ISK, kr, 0
Jamaican Dollar - JMD, $, 2
Jordanian Dinar - JOD, د.ا.‏, 3
Japanese Yen - JPY, ¥, 0
Kenyan Shilling - KES, Ksh, 2
Kyrgystani Som - KGS, сом, 2
Cambodian Riel - KHR, ៛, 2
South Korean Won - KRW, ₩, 0
Kuwaiti Dinar - KWD, د.ك.‏, 3
Kazakhstani Tenge - KZT, ₸, 2
Laotian Kip - LAK, ₭, 0
Lebanese Pound - LBP, ل.ل.‏, 2
Sri Lankan Rupee - LKR, රු., 2
Libyan Dinar - LYD, د.ل.‏, 3
Moroccan Dirham - MAD, د.م.‏, 2
Moldovan Leu - MDL, L, 2
Macedonian Denar - MKD, ден, 2
Myanmar Kyat - MMK, K, 0
Mongolian Tugrik - MNT, ₮, 0
Macanese Pataca - MOP, MOP, 2
Maldivian Rufiyaa - MVR, ރ., 2
Mexican Peso - MXN, $, 2
Malaysian Ringgit - MYR, RM, 2
Nigerian Naira - NGN, ₦, 2
Nicaraguan Córdoba - NIO, C$, 2
Norwegian Krone - NOK, kr, 2
Nepalese Rupee - NPR, रु, 2
New Zealand Dollar - NZD, $, 2
Omani Rial - OMR, ر.ع.‏, 3
Panamanian Balboa - PAB, B/., 2
Peruvian Sol - PEN, S/, 2
Philippine Piso - PHP, ₱, 2
Pakistani Rupee - PKR, Rs, 2
Polish Zloty - PLN, zł, 2
Paraguayan Guarani - PYG, ₲, 0
Qatari Rial - QAR, ر.ق.‏, 2
Romanian Leu - RON, lei, 2
Serbian Dinar - RSD, дин., 2
Russian Ruble - RUB, ₽, 2
Rwandan Franc - RWF, RF, 0
Saudi Riyal - SAR, ر.س.‏, 2
Swedish Krona - SEK, kr, 2
Singapore Dollar - SGD, $, 2
Somali Shilling - SOS, S, 0
Syrian Pound - SYP, ل.س.‏, 2
Thai Baht - THB, ฿, 2
Tajikistani Somoni - TJS, смн, 2
Turkmenistani Manat - TMT, m., 2
Tunisian Dinar - TND, د.ت.‏, 3
Turkish Lira - TRY, ₺, 2
Trinidad and Tobago Dollar - TTD, $, 2
New Taiwan Dollar - TWD, NT$, 2
Ukrainian Hryvnia - UAH, ₴, 2
US Dollar - USD, $, 2
Uruguayan Peso - UYU, $, 2
Uzbekistani Som - UZS, сўм, 0
Venezuelan Bolívar - VES, Bs.S, 2
Vietnamese Dong - VND, ₫, 2
Central African CFA Franc - XAF, FCFA, 0
East Caribbean Dollar - XCD, EC$, 2
Special Drawing Rights - XDR, XDR, 2
West African CFA Franc - XOF, CFA, 2
Yemeni Rial - YER, ر.ي.‏, 2
South African Rand - ZAR, R, 2
```
and in dev takes 00:00:00.0188823 to produce (once, it's shared).  This list becomes the default and attempts to add these to other providers will be ignored, and the default currencies will always be used.

**Comment by bleroy** [comment]
Yes, that sounds good. If we have that data, there's no reason not to make it part of the default provider. Like for cultures, there are reasons to add new ones, but not to replace. There are some implementation details around serialization, but that shouldn't affect you. Thanks for offering to contribute this.

**Comment by Allann** [comment]
Added new pull request  https://github.com/OrchardCMS/OrchardCore.Commerce/pull/44

**Comment by Allann** [comment]
Pull request merged
