### ISSUE TITLE
GitHub Actions Tests fails for Windows (OCC-238)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#433]
### Describe the bug

Build and Test (Windows) fails with a timeout for the main branch. 
https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/8804049904/job/24378106668

[Jira issue](https://lombiq.atlassian.net/browse/OCC-238)

**Comment by Piedone** [comment]
That should be this issue: https://github.com/Lombiq/UI-Testing-Toolbox/issues/358
