### ISSUE TITLE
How to get contentItem of product from contentItem of the order ,please? (OCC-240)

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore.Commerce#437]
### Describe the bug

I want to render a link to product contentItem in order list page, but How to get contentItem of product from contentItem of the order ,please?

[Jira issue](https://lombiq.atlassian.net/browse/OCC-240)

**Comment by sarahelsaig** [comment]
Hi,

it you mean in the OrderPart.cshtml, the order contains the product SKUs in the `Model.LineItems[i].ProductSku`. A simple example to fetch and display the product summary from the SKU:
```
@inject IProductService ProductService

@foreach (var item in Model.LineItems)
{
    var productPart = await ProductService.GetProductAsync(item.ProductSku);
    ...
}
```
Internally the order only stores the SKU and not the ContentItemVersionId, so this will always return the latest product version. The Model.LineItems contains the price at the time of payment so you can combine the two sources inside OrderPart.cshtml.
