### ISSUE TITLE
What is the status for the OchardCore.Commerce now?

### ISSUE THREAD

**Issue by haohello** [OrchardCMS/OrchardCore.Commerce#45]
I'm wondering if you can put together a roadmap with a list of issues for this project, so anyone interested can take part in the project. It is now seems to be moving too slow.

**Comment by jeffolmstead** [comment]
The [Minimum viable product (MVP)](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/3) is the current roadmap. Currently, Checkout is on the docket. 

As to "moving too slow", I suppose that is is all in perspective. I am pretty sure everyone that has put work on this is doing it on the side of their regular work. Often, contributions have to align with a need we have in our work place (e.g. I have a branch where I am working on [price books](https://github.com/OrchardCMS/OrchardCore.Commerce/tree/priceBooks) as I have a need for that). Some are also contributing to OrchardCore which is pushing to get a 1st official release. @bleroy has carried this project thus far and I am grateful. 

If you would like to jump in and contribute, it would be appreciated. It is a great community.

**Comment by bleroy** [comment]
Exactly. The project is moving as fast as contributors can make it move. Keep in mind, nobody's getting paid to work on this. As I always say, if that is too slow for your requirements, that's fine. I'd encourage to do one of two things: contribute and make it go faster, or use another, mature product such as NopCommerce.
