### ISSUE TITLE
Create REST API endpoints for main features (OCC-253)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#450]
Currently, there is no way to control shopping cart, checkout through an ApiController, REST API endpoint.

What's missing:
1. Shopping cart:
- Get shopping cart
- Add item
- Remove item
- Update line item, or shopping cart update

2. Checkout process

[Jira issue](https://lombiq.atlassian.net/browse/OCC-253)

**Comment by Piedone** [comment]
Maybe not with an ApiControllet but a potentially more efficient minimal API endpoint, see e.g. https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Modules/OrchardCore.Contents/Endpoints/Api. See rationale and metrics: https://github.com/OrchardCMS/OrchardCore/pull/15294.

**Comment by sarahelsaig** [comment]
> Hi : any update by somebody?

Not yet. We will certainly do this eventually. But in the meantime if you want to contribute (even partially) or make further suggestions here, that's also welcome.

> for shopping cart ,( or add Item) , I think we need User info. ( for ex. user token) for the api. currently, we use user session for the shopping cart , is it ok for multi-instances of OC or the client app?

There should be an OpenID Connect or JWT bearer token which is required to connect ([see info about `AuthenticationSchemes` in ASP.NET Core docs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-8.0)). OC's OpenID Server module can provide either type. This is not related to the shopping cart ID, which is optional. But you make a good point about the session storage, connecting through API will likely require a different `IShoppingCartPersistence` implementation.

> BY THE WAY, IT SEEMS THAT WE DID NOT USE shoppingCartId in whole project

I think we only don't use it in specific payment provider implementations that don't support multiple shopping carts. If you find it missing somewhere else too, please point it out.
