### ISSUE TITLE
There is a error that method 'DiscoverAsync' does not have an implementation after upgrating to v2.1.0.0 (OCC-254)

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore.Commerce#452]
### Describe the bug

AggregateException: One or more errors occurred. (Method 'DiscoverAsync' in type 'OrchardCore.Commerce.Services.AddressUpdaterShapeTableProvider' from assembly 'OrchardCore.Commerce.ContentFields, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
System.Threading.Tasks.TaskReplicator.Run<TState>(ReplicatableUserAction<TState> action, ParallelOptions options, bool stopOnFirstFailure)

TypeLoadException: Method 'DiscoverAsync' in type 'OrchardCore.Commerce.Services.AddressUpdaterShapeTableProvider' from assembly 'OrchardCore.Commerce.ContentFields, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.RuntimeAssembly.GetExportedTypes()

### To Reproduce

1. Upgrade to v2.1.0.0
2. Run project
3. Throw the error

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51013754/33796663-cdae-4589-b0d6-6b307b67671b)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-254)

**Comment by sarahelsaig** [comment]
What version of Orchard Core are you using? `IShapeTableProvider.Discover` has been removed in favor of `DiscoverAsync` [in the preview versions](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/IShapeTableProvider.cs) of Orchard Core. But as of the latest official release (v1.8.3), [it is still there](https://github.com/OrchardCMS/OrchardCore/blob/v1.8.0/src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/IShapeTableProvider.cs) along with the default value of `DiscoverAsync`, meaning that you don't have to implement it in derived methods.

**Comment by effapp** [comment]
> What version of Orchard Core are you using? `IShapeTableProvider.Discover` has been removed in favor of `DiscoverAsync` [in the preview versions](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/IShapeTableProvider.cs) of Orchard Core. But as of the latest official release (v1.8.3), [it is still there](https://github.com/OrchardCMS/OrchardCore/blob/v1.8.0/src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/IShapeTableProvider.cs) along with the default value of `DiscoverAsync`, meaning that you don't have to implement it in derived methods.

Hi @sarahelsaig,

      Version of Orchard Core is 2.0.0-preview-18218

**Comment by sarahelsaig** [comment]
Yes, that won't work. Regardless of the problem mentioned above, OC 2.0 has several breaking changes, including migration from Newtonsoft.Json to System.Text.Json. This is known to break some existing serialization in OCC and we can't patch it in main until OC 2.0 is released.

The NuGet releases of OrchardCore.Commerce are only meant to be compatible with the latest NuGet releases of OrchardCore. Please downgrade to OC 1.8.3.
