### ISSUE TITLE
Re-evaluate use CreateModelMaybeAsync (OCC-280)

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore.Commerce#479]
Suggestion based on quick review of code. The method `CreateModelMaybeAsync` should no longer be used

More about the reasoning can be found [here](https://github.com/Lombiq/Helpful-Libraries/issues/280)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-280)

**Comment by sarahelsaig** [comment]
When the driver is converted from `SectionDisplayDriver` to `SiteDisplayDriver`, the `groupId` parameter may be removed (set to `null`) in the method call. No other action is necessary.
