### ISSUE TITLE
How can I add more fields to part , such as ProductPart (OCC-291)

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore.Commerce#492]
### Is your feature request related to a problem? Please describe
Taks ProductPart as example:
I need 1--public MediaField ProductImage { get; set; }
2--public MediaField SecondaryProductImage { get; set; }
3--public VideoField PrimaryProductVideo { get; set; }
### Describe the solution you'd like
public partial class ProductPart

[Jira issue](https://lombiq.atlassian.net/browse/OCC-291)

**Comment by sarahelsaig** [comment]
It's not possible to add new fields to an existing content part in Orchard Core. Each content part is a single C# class, which can't be expanded in the consuming assembly. This is a limitation of .NET itself.

If you want to add more fields, you can create a new content part for them and add it to the existing content type. For example you can create a `ProductMediaPart` which contains the above mentioned fields. Then in migration, you can add this new content part to the same content type that also has `ProductPart`.
