### ISSUE TITLE
Product, price, and inventory parts and fields

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/OrchardCore.Commerce#5]
Those parts and fields implement the basic building blocks for products that can't be found in the core parts provided by Orchard Core itself. The parts should apply the single responsibility principle, for easier composition.

## Product part

This is largely a marker part, used primarily to identify a content type as a product. Its only property is:

* [**Sku**](https://en.wikipedia.org/wiki/Stock_keeping_unit) (string)

## Price part and field

Represents a price, using the following properties:

* **Amount** (decimal)
* **Currency**

## Inventory

Tracks the number of available items.

* **Inventory** (int) The number of items in stock.
* **AllowsBackOrder** (bool) If true, ordering is allowed even if Inventory is less or equal to zero.
* **OutOfStockMessage** (string) Enables a specific message for an out of stock product (can be used to give an ETA).
* **ConsiderInventory** (bool) True by default. If false, inventory is ignored. This is useful for digital products for example.
* **MinimumOrderQuantity** (int) 1 by default. The minimum number of this item one can order.

**Comment by jeffolmstead** [comment]
Two elements that I have encountered (not sure if Product is best place) are:

- Some products require "authentication" to purchase. Anyone can view, but must be logged in to buy. This tends to occur on digital products but there can be other cases where you want the order to be tied to a user account 
- Some products are "digital" and if all that is in the shopping cart are "digital" items the whole shipping section can be skipped during checkout.

I am not sure the best place for those two "fields".

**Comment by MatteoPiovanelli-Laser** [comment]
In nwazet we had those. The digital concern was handled through two flags: one telling that the product was digital, one that inventory should be ignored.

I am not 100% on PricePart.
For a Pay-what-you-want scenario, the part wouldn't have a value for the price. 

Inventory:
detaching it from products makes the `ConsiderInventory` flag redundant, I think.

**Comment by bleroy** [comment]
* Digital flag: that may be the same as not having inventory or having `ConsiderInventory` off. Let's consider what it would really do, that would be different. Also, there's always the possibility of having a Boolean field called "digital". We should only add this if it brings value.
* Authentication required: I'm wondering if we should open up an extensibility point for strategies that can decide whether a product can be purchased. Authentication would just be a specific implementation.
* Pay what you want: should this be a separate part, or even just a Boolean field, and we have an extensibility point for price-determining strategy that this plugs into?

General remark: whenever we have an extensibility point that strategies can plug into, we should consider what workflow activities we would need so a strategy can be built from the workflow editor. Commerce in my experience is done with a lot of custom rules that vary from shop to shop.

**Comment by jeffolmstead** [comment]
I think @bleroy general remarks hit the nail on the head, I envision this being the best commerce solution if is extensible (to other developers / features) and has good workflow integration. Every implementation I have done always needs "something different".

**Comment by bleroy** [comment]
Yes, Orchard workflows are awesome, and would give commerce an edge. It really is something special.

**Comment by MatteoPiovanelli-Laser** [comment]
> Authentication required: I'm wondering if we should open up an extensibility point for strategies that can decide whether a product can be purchased. Authentication would just be a specific implementation.

I like this.

> Pay what you want: should this be a separate part, or even just a Boolean field, and we have an extensibility point for price-determining strategy that this plugs into?

I see this as a sort of implementation of an IPricePart. Something like that. The price need to be something that can be manipulated by other stuff in the ecommerce anyway (promotions and such)

**Comment by bleroy** [comment]
Exactly. And workflows.

**Comment by lukaskabrt** [comment]
Few ideas about products ...

* it should be possible to specify the price of the single product in multiple currencies, this concept should be independent of product localization, because the same currency can be used for multiple languages . There might be a service `ICurrencySelector` that selects the currency for the customer based on various environment variables (e.g. Territory)
* product should have a VAT category and the price should indicate whether it includes VAT or not (not sure if it should be specified for every individual price - so user can once enter price with VAT and once without VAT, or globally across the whole web - all prices are either with VAT or without VAT)

**Comment by bleroy** [comment]
Those are both relatively advanced scenarios that need to be taken into account in order to design the right extensibility points, but don't necessarily need to be part of the MVP. More specifically, the price interfaces I already built should be able to address your first scenario through an extension. It would be a good exercise, actually, to verify that we have the right abstractions in place. The VAT one may be part of the default implementation of a tax subsystem, that would absolutely be part of the MVP. Let's add tax as a work item. I'm thinking we'll need shipping and taxes added to the MVP.

**Comment by TRiV07** [comment]
Another one important thing for product is attributes combinations price.
Simple example:
- T-Shirt Color:Green, Size:M - Price: $10
- T-Shirt Color:Green, Size:XL - Price: $12
- T-Shirt Color:Red, Size:XL - Price: $50

**Comment by bleroy** [comment]
Agreed. I have the project of having price-modifying attributes at some point in the future. Current work is on checkout though, so it might take a while. If somebody wants to give that a shot now however, I have thought about it quite a lot and can explain how I think it should be done.

**Comment by TRiV07** [comment]
Created simple implementation of my vision of attributes combinations price #47 
![1](https://user-images.githubusercontent.com/5490329/72159606-64be7a00-33c5-11ea-9307-7d89004afa8d.png)
![2](https://user-images.githubusercontent.com/5490329/72159607-64be7a00-33c5-11ea-91d4-95836cfeba1a.png)

**Comment by bleroy** [comment]
Thanks, I'll take a look later tonight or this week-end. Screenshot looks great.

**Comment by chinasqzl** [comment]
Different variants should have their own SKU
![image](https://user-images.githubusercontent.com/16968103/150240325-7e7acfb8-6dbc-4379-a812-ffe2226f4ef9.png)

**Comment by bleroy** [comment]
A good approach may be to have a variant sku similar to @TRiV07 's variant prices.

**Comment by mwpowellhtx** [comment]
With government and corporate scarcity policies going on, might also consider:

## Inventory
* `MaximumOrderQuantity` (`int?`) `null` by default. The maximum number of this items one can order.

**Comment by mwpowellhtx** [comment]
I agree with the above, different variant, has its own SKU.

**Comment by DAud-IcI** [comment]
Since ProductPart and PricePart already exist, I have opened a separate issue for inventory management, with the summary of the relevant discussion here. This is to make things cleaner for the roadmap. Please check it out and share your thoughts: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/134

I have also opened an issue for the topic of variant SKUs here as it didn't have one yet: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/135
