### ISSUE TITLE
PNPM `lockfileVersion` is 9.0 while should be 6.0 (OCC-303)

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore.Commerce#505]
### Describe the bug

`lockfileVersion` in pnpm-lock files are 9.0. However, the PNPM version shipped with the latest LTS Node version, [as instructed to be installed by Node.js Extensions](https://github.com/Lombiq/NodeJs-Extensions?tab=readme-ov-file#prerequisites), is 6.0. Because of this, you'll get diffs if you build the app:

![{89693207-7E39-4557-8FBC-7004F8EE4365}](https://github.com/user-attachments/assets/1714dd59-e12d-4147-bde9-02a641466737)

### To Reproduce

1. Open cleaned the solution with Node.js v20.x.
2. Build.
3. Notice many pnpm-lock.yml changes.

### Expected behavior

No changes after build

### Screenshots

See above.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-303)

**Comment by sarahelsaig** [comment]
omg I accidentally committed this into `dev`! :scream_cat:
It keeps making this change in every build, so I usually put it into a local branch to leave me alone and revert later.

**Comment by Piedone** [comment]
If you use Node 20 under Linux (like with NVM), it should still use v6 lock files, since that's what the PNPM version bundled with that Node supports.
