### ISSUE TITLE
Price Variants Not Working?

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore.Commerce#55]
I don't see how Price Variants can work currently. In the PriceVariantService "GetPriceVariants" method, you have this:

```
return keys
    .Where(key => part?.Variants?.ContainsKey(key) == true)
    .ToDictionary(key => key, key => part.Variants[key]);
```

Since I can never get anything stored in part.Variants (because the editor will never load any variants due to this line) it seems like variants are unusable. Am I missing something?

Also, does PriceVariant require the use of PricePart? My module I am building for Price Books replaces PricePart with multiple pricing options via a Price Book approach. I just want to know if the expectation is that a "PricePart" is always present on a product. Thanks for feedback (will save me time requesting to merge later).

**Comment by bleroy** [comment]
I don't understand the first part. How does it not work?

PriceVariant does not require the use of PricePart.

**Comment by jeffolmstead** [comment]
Steps I used:
1. Create Product Content Type
2. Add "Product Attribute Field" (I chose "Text Product Attribute")
3. Add a couple options in the "Product Attribute Field"
3. Add "PriceVariants" Content Part

When I create a new Product, none of the price variant options render:
![image](https://user-images.githubusercontent.com/1848585/74703084-14171980-51da-11ea-866a-481663691203.png)

```
__priceVariantsService.GetPriceVariants(part.ContentItem)
```
always returns empty results due to the line above:
```
return keys
    .Where(key => part?.Variants?.ContainsKey(key) == true)
    .ToDictionary(key => key, key => part.Variants[key]);
```

Because, even though I start out with "keys", the part?.Variants? is null (and appears it will always be null since the Editor will never show the options) so it won't contain any keys to return as a dictionary. Does that help?

**Comment by bleroy** [comment]
Yes, it does, thanks. @TRiV07, do you want to take this one?

**Comment by TRiV07** [comment]
> Yes, it does, thanks. @TRiV07, do you want to take this one?

In progress

**Comment by TRiV07** [comment]
Created pull request: https://github.com/OrchardCMS/OrchardCore.Commerce/pull/57

**Comment by bleroy** [comment]
Can we close this now?
