### ISSUE TITLE
When OrchardCore.Commerce is production stable?

### ISSUE THREAD

**Issue by aprokopyev** [OrchardCMS/OrchardCore.Commerce#59]
How can you compare you OrchardCore.Commerce readiness to nopCommerce?

https://www.nopcommerce.com/

What advantages are of using OrchardCore.Commerce over nopCommerce + Orchard with a SSO (single sign on) module like LDAP, OpenAuth, FIDO2, etc. ?

**Comment by aprokopyev** [comment]
Why none of public CMS and/or e-commerce system are based on a business frameworks like CSLA or DevExpress XAF?

**Comment by Skrypt** [comment]
Here an other one : https://github.com/dotnet-architecture/eShopOnContainers

**Comment by bleroy** [comment]
> How can you compare you OrchardCore.Commerce readiness to nopCommerce?

We're not. If anybody is doing that, they should stop.

> What advantages are of using OrchardCore.Commerce over nopCommerce + Orchard with a SSO (single sign on) module like LDAP, OpenAuth, FIDO2, etc. ?

At this time, there are none.

> Why none of public CMS and/or e-commerce system are based on a business framework like CSLA or DevExpress XAF?

I don't know. Make one?
