### ISSUE TITLE
Problem in using this module

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore.Commerce#61]
i have added this module to my project (not in OC source prj). but it doesn't appear in features to enable it.

these is my project config:

 ```

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>

  <ItemGroup> 
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-12962" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\module\OrchardCore.Commerce\OrchardCore.Commerce.csproj" />
    <ProjectReference Include="..\Theme\ProfileTheme\ProfileTheme.csproj" />
  </ItemGroup>
```

**Comment by bleroy** [comment]
It builds fine and you see nothing in the logs?

**Comment by aghili371** [comment]
no errors no logs.
it is strange it doesn't appear in features. i have all modules activated.

i created new project again:
dotnet new occms --logger serilog 

I downloaded the OrchardCore.Commerce in new location.

then I solved the OrchardCore.Commerce  project:
 ```
 <ItemGroup>
    <PackageReference Include="OrchardCore.ContentTypes" Version="1.0.0-rc1-12971" />
  </ItemGroup>

  <ItemGroup>
 
    <ProjectReference Include="MoneyDataType\MoneyDataType.csproj" />
  </ItemGroup>
```

then added this project as references to the main project.

what I should do else?

**Comment by bleroy** [comment]
One thing to try would be to attach a debugger and take a look at the loaded modules window, check if you see the commerce dll as loaded.

**Comment by bleroy** [comment]
Also, what do you mean "solved the OrchardCore.Commerce project"? You shouldn't have to touch that.

**Comment by aghili371** [comment]
> Also, what do you mean "solved the OrchardCore.Commerce project"? You shouldn't have to touch that.

I just added "    <ProjectReference Include="..\shop\OrchardCore.Commerce.csproj" />" this project to commerce project.

**Comment by aghili371** [comment]
> One thing to try would be to attach a debugger and take a look at the loaded modules window, check if you see the commerce dll as loaded.

no it doesn't load this DLL

**Comment by aghili371** [comment]
Please test it in a new solution with nugget packages.
it looks it needs somethings else.

i tested with another project which I have my modules on it. it doesn't load anyway.

**Comment by bleroy** [comment]
I'm confused about your repro steps. The module at this stage of its development must be compiled with the rest of the Orchard Core solution (see the readme). It's very early and not ready to be used as is, so I'm not sure how useful it would be to you outside of a dev environment.

**Comment by aghili371** [comment]
@bleroy what i need to add in this project to use it out of OC dev environment? i need to use this base for my shop.

**Comment by bleroy** [comment]
I'm afraid the module is not ready to be used in production, unless you are ready to do a lot of dev work on it, in which case you also need a dev environment, and then to deploy the results of that.
I'm sorry this is probably not the answer you'd like to hear,  but that's the current status for this module. If you need a commerce platform that is usable today, I'd encourage you to use a mature platform such as nopCommerce.

**Comment by aghili371** [comment]
@bleroy thank you very much. i know that. so I will use nop commerce.
