### ISSUE TITLE
Unable to build OrchardCore project after adding OrchardCore.Commerce

### ISSUE THREAD

**Issue by DrewBrasher** [OrchardCMS/OrchardCore.Commerce#63]
I followed the instructions for setting up the dev environment but at step 5 I get this error:

> Unable to find project information for 'C:\Working\OrchardCore\src\OrchardCore.Modules\OrchardCore.Commerce\MoneyDataType\MoneyDataType.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.

![OrchardCoreError](https://user-images.githubusercontent.com/9272802/89853371-dc6ca700-db56-11ea-9a8d-61f724ea9035.png)

I would like to help work on this module in any way I can.  I'm new to Orchard but have been doing .net development for 6 years and have been using .net core since it was first released.

**Comment by jeffolmstead** [comment]
There is another project in this solution for the MoneyDataType - you can find it [here](https://github.com/OrchardCMS/OrchardCore.Commerce/tree/master/MoneyDataType). Please just make sure your setup has the OrchardCore.Commerce project referencing the MoneyDataType project and it should compile then. Let me know if you need more help / if I missed anything.

**Comment by DrewBrasher** [comment]
The OrchardCore.Commerce project was referencing the MoneyDataType project but I don't think Visual Studio will let you reference a project that is not part of the solution.  I got it to work by adding the MoneyDataType project to the solution under the src folder.

**Comment by jeffolmstead** [comment]
Good feedback! I have closed this issue but feel free to open it again if need be.

**Comment by bleroy** [comment]
I think this is a consequence of the dev environment for the module not being stabilized. Eventually, what we should have is that the project stands on its own and doesn't need to be setup inside an Orchard Core clone. It should reference Orchard as packages instead, and build as a package that can then be imported into the user's Orchard projects. If someone wants to take that work, it can be a good way to familiarize yourself with the codebase.

**Comment by DrewBrasher** [comment]
@bleroy I would be happy to work on that.  I would like to get involved in the development of OrchardCore and particularly this module.  I started building my own CMS built on .net core a few years ago but have recently been thinking that my time would be better spent contributing to an existing one instead.  From what I've seem of OrchardCore so far it seems great!

**Comment by bleroy** [comment]
Great, I created this work item. Feel free to assign to yourself: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/64

There's also this follow-up, which is to build packages as an output, to which I'd add configuring GH actions to run tests as part of CI: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/42

**Comment by DrewBrasher** [comment]
I don't think I have access to assign the issues to myself.

**Comment by bleroy** [comment]
Yeah, that's weird. It looks like you'd need to be a member of the OrchardCMS org, which doesn't make much sense to me but eh. OK, so let me wave my magic wand: you're it. Feel free to call dibs with a comment there as well, but we can be very informal, that's fine.
