### ISSUE TITLE
Build against Orchard packages instead of project references

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/OrchardCore.Commerce#64]
Currently, the dev environment for the module is suboptimal, requiring a local clone of Orchard. Instead, we should reference Orchard Core NuGet packages, and make development as simple as cloning the repo and building.

**Comment by DrewBrasher** [comment]
I will work on this.

**Comment by DrewBrasher** [comment]
Is this what you had in mind?
https://github.com/DrewBrasher/OrchardCore.Commerce/tree/dev
If so, I will update the readme and create a pull request.

**Comment by DrewBrasher** [comment]
If you would rather the folder structure not be rearranged I can redo it without the new and moved folders.

**Comment by bleroy** [comment]
That looks great.

I would get rid of the "remove" item group in the project, I don't think we need it now.

I would clearly label the web project as a sample.

**Comment by DrewBrasher** [comment]
I did this on a fork of the master branch.  Should I have forked the checkout-process branch instead?  It's not a lot to redo if it would be better to start with that branch since the folder rearranging might make it hard to merge.

**Comment by bleroy** [comment]
I almost suggested that, then I thought it was a little unfair to place that burden on you, especially since this is work in progress, but if it's not a lot of work, then yes, that would be very helpful.

**Comment by DrewBrasher** [comment]
It's no problem.  I will do that.

**Comment by bleroy** [comment]
I just pushed my latest changeset...

**Comment by DrewBrasher** [comment]
How does this look: now: https://github.com/DrewBrasher/OrchardCore.Commerce/tree/dev

**Comment by bleroy** [comment]
:shipit:
