### ISSUE TITLE
ShoppingCart not deserializing

### ISSUE THREAD

**Issue by linnhecreative** [OrchardCMS/OrchardCore.Commerce#68]
Hi there

I'm just getting up to speed on this project and doing some testing.

I seem to have come across an issue where the cart isn't deserializing from the JSON stored in session, the json string is passed in however results in an empty ShoppingCart object. I've been through everything exhaustively and can't seem to get to the root of the problem.

Can anyone shed some light on this for me please?

https://github.com/OrchardCMS/OrchardCore.Commerce/blob/77d0ea2c122d973ba3e81be7dfa9df437c4a794f/OrchardCore.Commerce/Services/ShoppingCartHelpers.cs#L85

Thanks!

**Comment by bleroy** [comment]
Thanks for the report, but can you give more details about how to reproduce this? Ideally, set a breakpoint and catch the value of `deserializedCart`, then paste it here.

**Comment by linnhecreative** [comment]
Hi, I've set up the solution from the latest code and created a product via the Product recipe.
When I build and run, navigate to the product page, Add to cart, I'm then taken to the cart which displays "Your shopping cart is empty."

The <code>serializedCart</code> from session is correct and valid:

<pre>
{
	"Items": [
		{
			"quantity": 1,
			"sku": "test-22",
			"prices": [
				{
					"priority": 0,
					"amount": {
						"value": 500,
						"currency": "EUR"
					}
				}
			],
			"attributes": {}
		}
	],
	"Count": 1,
	"ItemCount": 1
}
</pre>


However, when the deserialization is attempted the <code>cart</code> object is instantiated, but empty:

![Screenshot 2020-09-24 at 08 18 42](https://user-images.githubusercontent.com/988373/94113358-aea99c00-fe3e-11ea-8e69-481402feaa55.png)

It looks like the deserialization is failing, however there's no exceptions and it seems like it doesn't even try as <code>Read</code> is never hit in the ShoppingCartItemConverter

**Comment by bleroy** [comment]
Fixed.
