### ISSUE TITLE
Cannot see commerce features on OrchardCore dev branch

### ISSUE THREAD

**Issue by giantpenguin** [OrchardCMS/OrchardCore.Commerce#69]
I try install Commerce module onto the current OrchardCore dev branch (later than stable master version) but cannot see its features.

Where should I look into to get it work?

Thanks All!

**Comment by bleroy** [comment]
Please follow the instructions in the readme.

**Comment by giantpenguin** [comment]
Thank for your rep!

What I aim is using commerce with the dev branch OrchardCore, so that I followed the instruction and then replaced the referenced packages with references of directly projects in the solution.

The issue is the commerce does not work with the dev branch OrchardCore, any idea???

**Comment by giantpenguin** [comment]
At last, I have managed to make it work. 
The commerce module (as other modules) MUST be placed in the "OrchardCore.Modules" file system folder. This is a requirement, and the corresponding guide should be in a **highlight**. 

Why a module must be in the "OrchardCore.Modules" file system folder? Any idea?

**Comment by bleroy** [comment]
Hi. A few things to keep in mind:
1. the module is still very far from being useful. There's no checkout process yet for instance. So you should only use it for experimentation or if you plan on contributing.
2. Orchard Core does module management very differently from Orchard 1.x. In 1.x, you could drop a module's source code into the modules folder of the site and it would pick it up and show it in the modules/features screen. Core does things very different. There is no dynamic compilation or auto-discovery. Instead, your web site is a regular ASP.NET project that you add references to. The correct way to add commerce is to add the commerce package to your web project. Except... we're not yet generating, let alone publishing packages with our builds (if someone wants to contribute that, it would be great). So the best way to test the module for the moment is to follow the readme instructions and run the sample project that's in there. Using it in another existing site would probably require first that you generate packages for the module and then add those to your project.
3. We work against the latest RC version of Orchard as available as packages on NuGet.org. Weused to work against a clone of the source code repo, but no longer, now it's all packages.

**Comment by giantpenguin** [comment]
Thank for your helpful reply, @bleroy!

At the moment I try to experiment it, try to contribute something later :)
