### ISSUE TITLE
Implement shopping cart for commercial project (OCC-73)

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore.Commerce#81]
We have built a presentational website for our client.
And now he wants a shopping cart with Visa/Mastercard payment.
User calculates a concrete blocks count https://betonera.ua/ua/calculator, adds the result to a shopping cart and does a check-out with ability to pay via card.
1 currency.

Is any one of contributors can complete required functionality of this module enough on commercial basis to implement our scenario?

We do not have developers qualified enough to do that. But they can be engaged and perform clearly defined tasks if you need. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-73)

**Comment by bleroy** [comment]
What's your timeline? Depending on what the customer will sell, you may be able to do a simple integration of a service such as Square in less time than it would take to land the feature here.

**Comment by xperiandri** [comment]
1-2 months would be good, but 3 is also acceptable

**Comment by xperiandri** [comment]
The customer also needs to create an order in his ERP system via REST.
So it would be great if this module can publish events to workflows.

**Comment by bleroy** [comment]
When it's implemented, it will absolutely be using workflows, yes.

OK, so let's try to find a good strategy for you. First, let me say that I'm not personally right now in a position to commit on delivering the feature with that timing, so your best bet would be to find a contractor or consultant in the Orchard community who would be available to do the work (and hopefully contribute it to the project, but I can't force anyone to do that, the license is very permissive intentionally). I'd start by posting on the main Orchard discussion boards, and maybe contact Lombiq and iDeliverable. I'll be happy myself to provide advice, review code, and contribute some code depending on my availability over the next few months.

Please do keep me posted. I hope this helps.

**Comment by xperiandri** [comment]
Thanks! Where are `Orchard discussion boards` located?

**Comment by bleroy** [comment]
https://github.com/OrchardCMS/OrchardCore/discussions and https://gitter.im/OrchardCMS/OrchardCore

**Comment by xperiandri** [comment]
@TRiV07 what about you?

**Comment by xperiandri** [comment]
@microposmp, @agriffard, @DrewBrasher

**Comment by Piedone** [comment]
@DAud-IcI this is already addressed I think?
