### ISSUE TITLE
.NET 6.0 application bootstrapping (OCC-71)

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore.Commerce#97]
As suggested by @jhgbrt

It would be a good thing to use the new way of bootstrapping the application in .NET 6.0
Maybe there is a way to use it even if we are multi-targeting frameworks on the CI.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-71)

**Comment by barthamark** [comment]
@DAud-IcI please confirm that this is addressed by https://github.com/OrchardCMS/OrchardCore.Commerce/pull/119

**Comment by DAud-IcI** [comment]
Nope, `SampleWebApp` still uses the generic host builder style. #119 didn't do functional changes unless it seemed necessary.

> Maybe there is a way to use it even if we are multi-targeting frameworks on the CI.

What other frameworks do you have in mind, @Skrypt ? I think we only need to target .Net 6, becuase that's what OC 1.3 requires.

**Comment by Skrypt** [comment]
Even though we currently only target net6.0 when net7.0 will be out we will probably multi-target to keep an LTS version in the build pipeline. So, you need to keep in mind that we are going to eventually multi-target.

**Comment by DAud-IcI** [comment]
Yes, that makes sense. I just got confused, becuase the new style application boostrapping should be forward-compatible so .Net 7 wouldn't have any effect on the issue topic.

We could take a look at multi-targeting with the [7.0.0-preview.3 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) (in a container, becuase installing preview SDKs on bare metal is never a good time). But that should be a separate issue, I think.

**Comment by Skrypt** [comment]
I believe this is why we dropped net3.1 and net5.0.

**Comment by sarahelsaig** [comment]
Looks like this was done during https://github.com/OrchardCMS/OrchardCore.Commerce/issues/212#issuecomment-1285748447 ([see the diff here](https://github.com/OrchardCMS/OrchardCore.Commerce/commit/e41ee9640393140567ddac1f8bf55dfd77d7f5f9#diff-a21402fc453e9a9827fb28f5519ac013fb2aa77c3c0a73c6ee2d8d1ffaac48d9))
